version: '3.4'

services:
  myworker:
    build: 
      dockerfile: MailQueue.Service/Dockerfile
      context: ./
    restart: always
    depends_on:
      - "rabbitmq"

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"